export const tokens = {
  colors: {
    accentPrimary: '#D4871C',
    surfacePrimary: '#FFFFFF',
    surfaceSecondary: '#F5F0EB',
    foregroundPrimary: '#1A1A1A',
    foregroundSecondary: '#6B6B6B',
    foregroundMuted: '#9E9E9E',
    borderSubtle: '#E5E0DB',
    success: '#4CAF50',
    error: '#F44336',
    white: '#FFFFFF',
    warmCream: '#FAF5EF',
    warmCreamDark: '#EDE5DA',
  },
  fonts: {
    primary: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  radii: {
    sm: '8px',
    md: '12px',
    lg: '16px',
    full: '9999px',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
  },
  fontSize: {
    xs: '12px',
    sm: '14px',
    md: '16px',
    lg: '18px',
    xl: '24px',
    xxl: '32px',
    xxxl: '40px',
  },
  shadows: {
    sm: '0 1px 2px rgba(0, 0, 0, 0.06)',
    md: '0 2px 8px rgba(0, 0, 0, 0.08)',
    lg: '0 4px 16px rgba(0, 0, 0, 0.12)',
  },
} as const;

// CSS custom properties map for use in global styles
export const cssVariables: Record<string, string> = {
  '--color-accent-primary': tokens.colors.accentPrimary,
  '--color-surface-primary': tokens.colors.surfacePrimary,
  '--color-surface-secondary': tokens.colors.surfaceSecondary,
  '--color-foreground-primary': tokens.colors.foregroundPrimary,
  '--color-foreground-secondary': tokens.colors.foregroundSecondary,
  '--color-foreground-muted': tokens.colors.foregroundMuted,
  '--color-border-subtle': tokens.colors.borderSubtle,
  '--color-success': tokens.colors.success,
  '--color-error': tokens.colors.error,
  '--color-white': tokens.colors.white,
  '--color-warm-cream': tokens.colors.warmCream,
  '--color-warm-cream-dark': tokens.colors.warmCreamDark,
  '--font-primary': tokens.fonts.primary,
  '--radius-sm': tokens.radii.sm,
  '--radius-md': tokens.radii.md,
  '--radius-lg': tokens.radii.lg,
  '--radius-full': tokens.radii.full,
  '--shadow-sm': tokens.shadows.sm,
  '--shadow-md': tokens.shadows.md,
  '--shadow-lg': tokens.shadows.lg,
};
